[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/tally/*"
  to = "/.netlify/functions/tally/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/confirm/*"
  to = "/.netlify/functions/confirm/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/chapters/*"
  to = "/.netlify/functions/chapters/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"