[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/tally/*"
  to = "/.netlify/functions/tally/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/confirm"
  to = "/.netlify/functions/confirm"
  status = 200
  force = true