<script lang="ts">
  import SkeletonPage from "./SkeletonPage.svelte";
  // import Page from "./Page.svelte";

  const { countdown, pageList, pageReached, currentPage, readingMode, revealNextPage } = $props();

  const visiblePages = $derived(pageList.filter(p => p.number <= pageReached));

  let backgroundColour: string = $state("bg-red-200");
  let fontSize: string = $state("text-base");

  // for these two, remember to add them to localStorage too
  const changeBackgroundColour = (newColour: string) => backgroundColour = newColour
  const changeFontSize = (newSize: string) => fontSize = newSize

  const whitespace = [
  {
    "page": 1,
    "content": "As I made some final touches to the last letter, I realized that I've written so much about the death of Jesus, I haven't written enough about his resurrection!  Jesus died to save us from our sins, but that's not where the story ends - there's more to it! The song of the day (listen to it as you read) is Resurrecting by Elevation Worship (Spotify, Apple Music).  Alright! For those new to the Christian faith, Jesus was a man who lived about two thousand years ago. We believe that he is the Son of God and the One who saved us from our sin and its consequences.  I wrote about this in my previous letter - Our Substitute. You should read it.  Now, for Jesus to save us from our sin, he had to sacrifice his life for ours. He took the full punishment for sin so we wouldn't have to go through it. He was beaten and scourged by Roman soldiers and then hung on a cross where He died.  Later that evening, a rich man in Jesus' time asked for his body, wrapped it in linen cloth, and placed it in a"
  },
  {
    "page": 2,
    "content": "new tomb.  The tomb was closed up with a very big stone and because Jesus had said many times that he would rise from the dead, the leading priests asked for Roman soldiers to guard the tomb so Jesus' followers wouldn't steal the body and claim that he had risen.  Whooshhhhh! You can find this entire story in the Bible - it's a collection of historical religious books (check online for a good bible app, I'd recommend YouVersion). The book of Matthew has this story in chapter 27, Mark in chapter 15, Luke in chapter 23, and John in chapter 19.  Where were we?  Friday evening, Jesus was buried. Some women prepared spices to anoint his body but by the time they were done the Sabbath had already started. They had to wait till Sunday - three days after.  Early Sunday morning, the women were on their way to the tomb and suddenly there was a great earthquake. They got to the tomb and saw the guards on the floor like dead men. The large stone sealing the tomb had been rolled away!   An angel"
  },
  {
    "page": 3,
    "content": "from the Lord had appeared to the guards and rolled the stone away. The women were terrified (I mean… who wouldn't). And the angel said to them -   Then the angel spoke to the women. “Don’t be afraid!” he said. “I know you are looking for Jesus, who was crucified. He isn’t here! He is risen from the dead, just as he said would happen. Come, see where his body was lying. Matthew 28:5  But the angel said, “Don’t be alarmed. You are looking for Jesus of Nazareth, who was crucified. He isn’t here! He has risen from the dead! Look, this is where they laid his body. Mark 16:6 NLT  The women were terrified and bowed with their faces to the ground. Then the men asked, “Why are you looking among the dead for someone who is alive? He isn’t here! He has risen from the dead! Remember what he told you back in Galilee, that the Son of Man must be betrayed into the hands of sinful men and be crucified, and that he would rise again on the third day.” Luke 24:5  Jesus rose from the dead! All through"
  },
  {
    "page": 4,
    "content": "his ministry, he told his disciples that he would die and rise again - and that's exactly what happened. What's funny though is that even his own disciples didn't believe.  The women, after seeing and hearing the angel's message, ran back to tell Jesus' disciples what had happened. But it all sounded like nonsense to them and they didn't believe it.  You can't blame them really. If you had seen Jesus' injuries from the scourging and the way he died on the cross, it would have taken a lot for you to believe that he could be alive again.  So some people don't.  They choose to believe that Jesus didn't actually die on the cross. That maybe he only fainted and entered a near-death state then afterwards he woke up and claimed to have resurrected.  This can't be true because the soldiers in charge of killing him were professionals and experts at killing. Before he got to the cross, the Roman soldiers had scourged him - beat him with whips made of leather thongs and pieces of metal"
  },
  {
    "page": 5,
    "content": "intertwined at various intervals. The whip would cause flesh to be torn and blood to pour out.  This resulted in major blood loss that put the victim into a state just short of death. After a brutal scourging like that, Jesus was then hoisted on a cross, hanging by nails from his wrist and suffering extreme suffocation because of the way victims were placed on the cross. You can't survive that.  And before his body was taken down from the cross, one of the soldiers pierced his side with a spear. Thrust from his side through to his chest, the spear most probably perforated his heart and damaged other internal organs. There's no other way to say this, Jesus truly died.  That's why even his disciples, those who had followed him for years and saw him do so many miracles didn't believe. Jesus had to appear to them before they could believe. The first person he appeared to was a woman named Mary Magdalene. She was part of the women who went to anoint his body at the tomb. When she ran back"
  },
  {
    "page": 6,
    "content": "to tell the disciples she had seen Jesus, they didn't believe.  He had to appear physically to his disciples. They were meeting behind closed doors because of fear of what the religious leaders would do to those who followed Jesus.   There in that room, He appeared to them!  The whole lot was terrified. They thought he was a ghost. Jesus showed them his injured hands with the nail prints and his feet - they were still in a state of disbelief. So he took a piece of broiled fish and ate it in front of them. JESUS WAS REALLY ALIVE!  One of the disciples, Thomas, wasn't with the others when Jesus appeared to them. When they told him, he said he wouldn't believe until he saw Jesus by himself (ever heard of doubting Thomas). Jesus appeared to him as well and then he believed - filled with wonder and awe.  Jesus appeared to other people too. Two gloomy men were on their way to a village called Emmaus. As the men talked, Jesus showed up and started to talk with them. He asked why they were sad"
  },
  {
    "page": 7,
    "content": "and they narrated how the leading priests had killed Jesus, the one they thought would be their savior.  Now, something amazing happens here - God doesn't allow these men to recognize Jesus!  Jesus was literally walking and talking with them but they didn't know it was him. Rather than allowing them to recognize him, Jesus showed them from their scriptures all the prophecies concerning the Saviour!  Those scriptures contained years of promises and prophecies about who the Saviour would be. It gave prophecies of the things the Saviour would do and what he would go through.  Jesus showed the men those prophecies and how he fulfilled all of them! Then he broke bread with them and their eyes were opened. They recognized who Jesus truly is - the One who saved us from our sins! (Our Substitute)  Share this Good News with someone! *share button*   In the beginning, when God created the first man and woman - Adam and Eve - He created them as perfect, holy beings. He created a garden and placed"
  },
  {
    "page": 8,
    "content": "them in it. He told them they could eat from all the fruits except the tree of knowledge of good and evil.  Welp, they didn't obey. They ate of the forbidden tree and that was when sin entered into the world (Genesis chapter 1 to 3). Sin is more than doing something wrong or bad, it's a state of being - a nature that everybody has as a result of eating from the forbidden tree.  This nature of sin in everyone severs our relationship with God and has a penalty - a punishment for it. The penalty for sin is death. Death is a result of sin!  When Adam sinned, sin entered the world. Adam’s sin brought death, so death spread to everyone, for everyone sinned. Romans 5:12 NLT   For the wages of sin is death... Romans 6:23 NLT   This is why we need a Savior! We couldn't save ourselves so we needed someone to save us. Someone who would make the atonement for our sin. Someone who would create a way for us to be forgiven and the nature of sin to be destroyed!  And that's what Jesus came to do.  But"
  },
  {
    "page": 9,
    "content": "then, anyone can claim to be the Savior. Good thing Jesus' claims came with proof - he rose from the grave! Jesus was crucified on the cross and three days after, he was raised back to life by the power of the Holy Spirit!  Now, during his time on Earth, Jesus raised people from the dead. One of them was his friend, Lazarus and you can find the story in the Book of John chapter 11. So if other people were raised from the dead, how come Jesus rising from the dead is proof that he's the Savior?  Well, Jesus never died again.  After appearing to many of his followers for forty days, he went with his disciples to a place called Bethany. There he told them to go and tell everyone the Good News - how he saved us from our sins.  When he finished speaking, as the disciples watched, he was taken into heaven, sat at the right hand of God and they could no longer see him. Jesus was alive when he was taken to heaven and he is still alive in heaven today!  Because Jesus cannot die again, it shows"
  },
  {
    "page": 10,
    "content": "that death and sin have no power over him! The Apostle Paul in one of his letters (you can find it in the Bible too) was writing to a church in Rome and explained it this way -  We are sure of this because Christ was raised from the dead, and he will never die again. Death no longer has any power over him. When he died, he died once to break the power of sin. But now that he lives, he lives for the glory of God. Romans 6:9  Jesus was born completely without sin. So when he got on the cross to pay the penalty for sin (our Substitute), it was our sin - the sin of the whole world - he was paying for!  For God made Christ, who never sinned, to be the offering for our sin, so that we could be made right with God through Christ. 2 Corinthians 5:21 NLT   This is Good News 🦅🦅🦅  Sin that used to be a problem, sin that had to be punished, sin that led to death was defeated by Jesus! Death used to be the final destination - but not anymore. Jesus paved the way through death and showed us that"
  },
  {
    "page": 11,
    "content": "there is life even after dying.  So you see, just as death came into the world through a man, now the resurrection from the dead has begun through another man. 1 Corinthians 15:21 NLT   People die because of sin - the original sin from the first man, Adam. And through another man, Jesus, we can be raised from the dead and live forever! That's the hope of the gospel and everything that Jesus has done for us.  And this new life we will receive is not a life that will continue in this present world. No, not in this world of pain and suffering. It will be like the Garden of Eden but even better.  I heard a loud shout from the throne, saying, “Look, God’s home is now among his people! He will live with them, and they will be his people. God himself will be with them. He will wipe every tear from their eyes, and there will be no more death or sorrow or crying or pain. All these things are gone forever.” Revelation 21:3  A life in a new world, a beautiful world with a life that never ends -"
  },
  {
    "page": 12,
    "content": "eternal life. That's what Jesus came to open up for us.  “For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. John 3:16 NLT   And all you have to do to be a part of what Jesus did is to simply believe. Jesus has already done everything for you and the Bible calls it a gift - the gift of salvation. Jesus offers you this gift through the message of the Good News - what I've just preached to you - and if you believe it, you are saved!  If you openly declare that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved. For it is by believing in your heart that you are made right with God, and it is by openly declaring your faith that you are saved. Romans 10:9  Glory to God 🦅  Jesus died for our sins and was raised to life to make us right with God. If you believe this, you are saved. Safe from hell and destruction - now seated with Jesus in heaven!  And I know"
  },
  {
    "page": 13,
    "content": "that it's not a dead hope, Jesus rose from the dead. So on that glorious day when he returns, whether I am alive or dead, I'll be resurrected and meet him in the clouds.  For the Lord himself will come down from heaven with a commanding shout, with the voice of the archangel, and with the trumpet call of God. First, the believers who have died will rise from their graves. Then, together with them, we who are still alive and remain on the earth will be caught up in the clouds to meet the Lord in the air. Then we will be with the Lord forever. 1 Thessalonians 4:16  Know someone who needs to hear this Good News? Share this letter with em'! *share button*  *add footnote (contains mail link)* **the Heartbeat Letters will be every two Sundays  The Heartbeat Letters is a bi-weekly Substack publication with one major purpose - telling the world about the Good News of Jesus Christ.  You can send me a mail here.  Till infinity, let your heart beat for Jesus 🌹 *Subscribe button*   ** I'm writing"
  },
  {
    "page": 14,
    "content": "a LETTER! It's only natural that I greet them. There's a way I write that's my way of writing, don't conform in style and structure."
  }
];

  const words = [
  {
    "page": 1,
    "content": "As I made some final touches to the last letter, I realized that I've written so much about the death of Jesus, I haven't written enough about his resurrection! Jesus died to save us from our sins, but that's not where the story ends - there's more to it! The song of the day (listen to it as you read) is Resurrecting by Elevation Worship (Spotify, Apple Music). Alright! For those new to the Christian faith, Jesus was a man who lived about two thousand years ago. We believe that he is the Son of God and the One who saved us from our sin and its consequences. I wrote about this in my previous letter - Our Substitute. You should read it. Now, for Jesus to save us from our sin, he had to sacrifice his life for ours. He took the full punishment for sin so we wouldn't have to go through it. He was beaten and scourged by Roman soldiers and then hung on a cross where He died. Later that evening, a rich man in Jesus' time asked for his body, wrapped it in linen cloth, and placed it in a new tomb. The tomb was closed up with a very big stone and because Jesus had said many times that he would rise from the dead, the leading priests asked for Roman soldiers to guard the tomb so Jesus' followers wouldn't steal the body and claim that he had risen. Whooshhhhh! You can find this"
  },
  {
    "page": 2,
    "content": "entire story in the Bible - it's a collection of historical religious books (check online for a good bible app, I'd recommend YouVersion). The book of Matthew has this story in chapter 27, Mark in chapter 15, Luke in chapter 23, and John in chapter 19. Where were we? Friday evening, Jesus was buried. Some women prepared spices to anoint his body but by the time they were done the Sabbath had already started. They had to wait till Sunday - three days after. Early Sunday morning, the women were on their way to the tomb and suddenly there was a great earthquake. They got to the tomb and saw the guards on the floor like dead men. The large stone sealing the tomb had been rolled away! An angel from the Lord had appeared to the guards and rolled the stone away. The women were terrified (I mean… who wouldn't). And the angel said to them - Then the angel spoke to the women. “Don’t be afraid!” he said. “I know you are looking for Jesus, who was crucified. He isn’t here! He is risen from the dead, just as he said would happen. Come, see where his body was lying. Matthew 28:5 But the angel said, “Don’t be alarmed. You are looking for Jesus of Nazareth, who was crucified. He isn’t here! He has risen from the dead! Look, this is where they laid his body. Mark 16:6 NLT The women were terrified and bowed with their faces"
  },
  {
    "page": 3,
    "content": "to the ground. Then the men asked, “Why are you looking among the dead for someone who is alive? He isn’t here! He has risen from the dead! Remember what he told you back in Galilee, that the Son of Man must be betrayed into the hands of sinful men and be crucified, and that he would rise again on the third day.” Luke 24:5 Jesus rose from the dead! All through his ministry, he told his disciples that he would die and rise again - and that's exactly what happened. What's funny though is that even his own disciples didn't believe. The women, after seeing and hearing the angel's message, ran back to tell Jesus' disciples what had happened. But it all sounded like nonsense to them and they didn't believe it. You can't blame them really. If you had seen Jesus' injuries from the scourging and the way he died on the cross, it would have taken a lot for you to believe that he could be alive again. So some people don't. They choose to believe that Jesus didn't actually die on the cross. That maybe he only fainted and entered a near-death state then afterwards he woke up and claimed to have resurrected. This can't be true because the soldiers in charge of killing him were professionals and experts at killing. Before he got to the cross, the Roman soldiers had scourged him - beat him with whips made of leather thongs and pieces of metal"
  },
  {
    "page": 4,
    "content": "intertwined at various intervals. The whip would cause flesh to be torn and blood to pour out. This resulted in major blood loss that put the victim into a state just short of death. After a brutal scourging like that, Jesus was then hoisted on a cross, hanging by nails from his wrist and suffering extreme suffocation because of the way victims were placed on the cross. You can't survive that. And before his body was taken down from the cross, one of the soldiers pierced his side with a spear. Thrust from his side through to his chest, the spear most probably perforated his heart and damaged other internal organs. There's no other way to say this, Jesus truly died. That's why even his disciples, those who had followed him for years and saw him do so many miracles didn't believe. Jesus had to appear to them before they could believe. The first person he appeared to was a woman named Mary Magdalene. She was part of the women who went to anoint his body at the tomb. When she ran back to tell the disciples she had seen Jesus, they didn't believe. He had to appear physically to his disciples. They were meeting behind closed doors because of fear of what the religious leaders would do to those who followed Jesus. There in that room, He appeared to them! The whole lot was terrified. They thought he was a ghost. Jesus showed them his injured hands with the"
  },
  {
    "page": 5,
    "content": "nail prints and his feet - they were still in a state of disbelief. So he took a piece of broiled fish and ate it in front of them. JESUS WAS REALLY ALIVE! One of the disciples, Thomas, wasn't with the others when Jesus appeared to them. When they told him, he said he wouldn't believe until he saw Jesus by himself (ever heard of doubting Thomas). Jesus appeared to him as well and then he believed - filled with wonder and awe. Jesus appeared to other people too. Two gloomy men were on their way to a village called Emmaus. As the men talked, Jesus showed up and started to talk with them. He asked why they were sad and they narrated how the leading priests had killed Jesus, the one they thought would be their savior. Now, something amazing happens here - God doesn't allow these men to recognize Jesus! Jesus was literally walking and talking with them but they didn't know it was him. Rather than allowing them to recognize him, Jesus showed them from their scriptures all the prophecies concerning the Saviour! Those scriptures contained years of promises and prophecies about who the Saviour would be. It gave prophecies of the things the Saviour would do and what he would go through. Jesus showed the men those prophecies and how he fulfilled all of them! Then he broke bread with them and their eyes were opened. They recognized who Jesus truly is - the One who"
  },
  {
    "page": 6,
    "content": "saved us from our sins! (Our Substitute) Share this Good News with someone! *share button* In the beginning, when God created the first man and woman - Adam and Eve - He created them as perfect, holy beings. He created a garden and placed them in it. He told them they could eat from all the fruits except the tree of knowledge of good and evil. Welp, they didn't obey. They ate of the forbidden tree and that was when sin entered into the world (Genesis chapter 1 to 3). Sin is more than doing something wrong or bad, it's a state of being - a nature that everybody has as a result of eating from the forbidden tree. This nature of sin in everyone severs our relationship with God and has a penalty - a punishment for it. The penalty for sin is death. Death is a result of sin! When Adam sinned, sin entered the world. Adam’s sin brought death, so death spread to everyone, for everyone sinned. Romans 5:12 NLT For the wages of sin is death... Romans 6:23 NLT This is why we need a Savior! We couldn't save ourselves so we needed someone to save us. Someone who would make the atonement for our sin. Someone who would create a way for us to be forgiven and the nature of sin to be destroyed! And that's what Jesus came to do. But then, anyone can claim to be the Savior. Good thing Jesus' claims came"
  },
  {
    "page": 7,
    "content": "with proof - he rose from the grave! Jesus was crucified on the cross and three days after, he was raised back to life by the power of the Holy Spirit! Now, during his time on Earth, Jesus raised people from the dead. One of them was his friend, Lazarus and you can find the story in the Book of John chapter 11. So if other people were raised from the dead, how come Jesus rising from the dead is proof that he's the Savior? Well, Jesus never died again. After appearing to many of his followers for forty days, he went with his disciples to a place called Bethany. There he told them to go and tell everyone the Good News - how he saved us from our sins. When he finished speaking, as the disciples watched, he was taken into heaven, sat at the right hand of God and they could no longer see him. Jesus was alive when he was taken to heaven and he is still alive in heaven today! Because Jesus cannot die again, it shows that death and sin have no power over him! The Apostle Paul in one of his letters (you can find it in the Bible too) was writing to a church in Rome and explained it this way - We are sure of this because Christ was raised from the dead, and he will never die again. Death no longer has any power over him. When he died, he died"
  },
  {
    "page": 8,
    "content": "once to break the power of sin. But now that he lives, he lives for the glory of God. Romans 6:9 Jesus was born completely without sin. So when he got on the cross to pay the penalty for sin (our Substitute), it was our sin - the sin of the whole world - he was paying for! For God made Christ, who never sinned, to be the offering for our sin, so that we could be made right with God through Christ. 2 Corinthians 5:21 NLT This is Good News 🦅🦅🦅 Sin that used to be a problem, sin that had to be punished, sin that led to death was defeated by Jesus! Death used to be the final destination - but not anymore. Jesus paved the way through death and showed us that there is life even after dying. So you see, just as death came into the world through a man, now the resurrection from the dead has begun through another man. 1 Corinthians 15:21 NLT People die because of sin - the original sin from the first man, Adam. And through another man, Jesus, we can be raised from the dead and live forever! That's the hope of the gospel and everything that Jesus has done for us. And this new life we will receive is not a life that will continue in this present world. No, not in this world of pain and suffering. It will be like the Garden of Eden but even better."
  },
  {
    "page": 9,
    "content": "I heard a loud shout from the throne, saying, “Look, God’s home is now among his people! He will live with them, and they will be his people. God himself will be with them. He will wipe every tear from their eyes, and there will be no more death or sorrow or crying or pain. All these things are gone forever.” Revelation 21:3 A life in a new world, a beautiful world with a life that never ends - eternal life. That's what Jesus came to open up for us. “For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. John 3:16 NLT And all you have to do to be a part of what Jesus did is to simply believe. Jesus has already done everything for you and the Bible calls it a gift - the gift of salvation. Jesus offers you this gift through the message of the Good News - what I've just preached to you - and if you believe it, you are saved! If you openly declare that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved. For it is by believing in your heart that you are made right with God, and it is by openly declaring your faith that you are saved. Romans 10:9 Glory to God 🦅 Jesus died for our sins and"
  },
  {
    "page": 10,
    "content": "was raised to life to make us right with God. If you believe this, you are saved. Safe from hell and destruction - now seated with Jesus in heaven! And I know that it's not a dead hope, Jesus rose from the dead. So on that glorious day when he returns, whether I am alive or dead, I'll be resurrected and meet him in the clouds. For the Lord himself will come down from heaven with a commanding shout, with the voice of the archangel, and with the trumpet call of God. First, the believers who have died will rise from their graves. Then, together with them, we who are still alive and remain on the earth will be caught up in the clouds to meet the Lord in the air. Then we will be with the Lord forever. 1 Thessalonians 4:16 Know someone who needs to hear this Good News? Share this letter with em'! *share button* *add footnote (contains mail link)* **the Heartbeat Letters will be every two Sundays The Heartbeat Letters is a bi-weekly Substack publication with one major purpose - telling the world about the Good News of Jesus Christ. You can send me a mail here. Till infinity, let your heart beat for Jesus 🌹 *Subscribe button* ** I'm writing a LETTER! It's only natural that I greet them. There's a way I write that's my way of writing, don't conform in style and structure."
  }
]
</script>

<div class="flex flex-col items-center py-1">
  <!-- {#each whitespace as page }
    <Page content={page.content} {backgroundColour} {fontSize} />
  {/each} -->

  {#each words as page }
    <!-- <Page content={page.content} {backgroundColour} {fontSize} /> -->
  {/each}
</div>


<!-- {#if readingMode === 'chapter'}
  <div class="flex flex-col items-center py-1">
    {#each visiblePages as page}
      <Page content={page.text} {backgroundColour} {fontSize} />
    {/each}

    <SkeletonPage {backgroundColour} {countdown} {revealNextPage}/>
  </div>
  
{/if}  -->
